-- Conteúdo publicado e versão para impedir sobrescrita entre duas abas.
CREATE TABLE home_content (
  id boolean PRIMARY KEY DEFAULT true CHECK(id),
  revision integer NOT NULL DEFAULT 1,
  content jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE media (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  data bytea NOT NULL CHECK(octet_length(data)<=500000),
  created_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO home_content(id,content) VALUES(true,'{"cards": [{"id": "palabras", "title": "Palabras que se quedan", "category": "Bordado", "alt": "Bastidor con frase bordada y pequeñas flores blancas", "description": "Una frase, unas flores y un lugar donde guardar lo que importa. Un ejemplo de cómo las palabras pueden convertirse en un recuerdo bordado.", "src": "/shop/embroidery.jpg", "visible": true}, {"id": "panda", "title": "Un abrazo de hilo", "category": "Ganchillo", "alt": "Panda de ganchillo con falda verde y pequeñas flores", "description": "Un pequeño personaje, hecho punto a punto. Sus colores y detalles son el comienzo de una conversación sobre tu próxima pieza.", "src": "/shop/panda.jpg", "visible": true}, {"id": "ilustracion", "title": "Historias en papel", "category": "Ilustración", "alt": "Selección de ilustraciones y encargos personales de Qalbi", "description": "Personas, lugares y pequeñas cosas que dicen mucho de ti. Una selección de encargos donde una idea personal encuentra su forma en la ilustración.", "src": "/shop/illustration.jpg", "visible": true}, {"id": "panuelos", "title": "Para un día inolvidable", "category": "Bordado", "alt": "Pañuelos claros bordados a mano con mensajes personales", "description": "Palabras para acompañar un momento especial. Estos pañuelos muestran cómo un mensaje personal puede convertirse en un regalo lleno de significado.", "src": "/shop/wedding.jpg", "visible": true}, {"id": "osito", "title": "Compañeros de aventuras", "category": "Ganchillo", "alt": "Lorrayne mostrando un osito de ganchillo con ropa azul y amarilla", "description": "Personajes con detalles propios, creados con tiempo y cariño. Cuéntame qué personaje imaginas y exploramos sus posibilidades.", "src": "/shop/bear.jpg", "visible": true}, {"id": "patitos", "title": "Pequeños, muy queridos", "category": "Ganchillo", "alt": "Lorrayne con dos patitos de ganchillo y detalles en malva", "description": "Detalles de ganchillo que acompañan una ocasión especial. Un punto de partida para pensar en un regalo con algo de esa persona.", "src": "/shop/lorrayne.jpg", "visible": true}], "photos": {"hero": {"src": "/shop/embroidery.jpg", "alt": "Bastidor Qalbi bordado a mano con flores y una frase"}, "story": {"src": "/shop/wedding.jpg", "alt": "Pañuelos bordados con mensajes personales"}, "portrait": {"src": "/shop/lorrayne.jpg", "alt": "Lorrayne, creadora de Qalbi Atelier, con sus patitos de ganchillo"}}}');
